# Generated by Django 5.2.4 on 2025-07-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('person_id', models.IntegerField()),
            ],
        ),
    ]
