# Generated by Django 5.2.4 on 2025-07-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250709_1213'),
    ]

    operations = [
    ]
