# Generated by Django 5.2.4 on 2025-07-09 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250709_1215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

   