# Generated by Django 5.2.4 on 2025-07-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_picture_person_id_picture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='my_choice_rating',
            field=models.IntegerField(choices=[(1, '😞 1 - Nagyon rossz'), (2, '😒 2 - Rossz'), (3, '😐 3 - Elmegy'), (4, '🙂 4 - Jó'), (5, '😍 5 - Tökéletes')], default=3),
        ),
    ]
