# Generated by Django 5.2.4 on 2025-07-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture_id',
        ),
        migrations.AddField(
            model_name='picture',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
